### ISSUE TITLE
Fatal Error in WooCommerce product editor with Gutenberg enabled

### ISSUE THREAD

**Issue by brandomeniconi** [Automattic/jetpack#10727]
This issue apperared after installing Jetpack 6.8, before it was working fine.

#### Steps to reproduce the issue

1. [Enable Gutenberg editor on WooCommerce products](https://wplook.com/how-to-enamble-gutenberg-for-woocommerce-products/)
2. Go to WooCommerce Products page in wp-admin
3. Create/Edit product with the Gutenberg Editor
4. See the fatal error specified below

#### What I expected

The page sould load with the Gutenberg editor

#### What happened instead
The page responds with error 500:
`Fatal error: Uncaught Error: Call to a member function current_user_can_access_publicize_data() on null in [..]/plugins/jetpack/_inc/lib/core-api/wpcom-fields/post-fields-publicize-connections.php:118`

**Comment by jeherve** [comment]
Thanks for the report!

Do you get the same error when trying to edit a blog post instead of a product?

Could you also let me know if the problem remains when deleting Jetpack and installing it again from scratch?

Thank you.

**Comment by jeherve** [comment]
I can't seem to be able to reproduce on my end with the most recent version of Gutenberg (4.5.1), nor with WordPress 5.0 RC1. If the problem remains on your end after reinstalling the plugin, could you let me know what versions of WooCommerce, Gutenberg, and WP you use on your site, and if you have any other plugins on that site?

Thank you.

**Comment by ockham** [comment]
Relevant line: https://github.com/Automattic/jetpack/blob/62e6883ee0767f3cfbea1c32b07fce69dd32fce0/_inc/lib/core-api/wpcom-fields/post-fields-publicize-connections.php#L118

**Comment by ockham** [comment]
> @ockham Maybe we could wrap it with a check, to be safe?

I'd like to find out why `$publicize` is `null` there, since there's a chance that there are also other instances where that's the case and that might cause us trouble (which wouldn't be fixed by one additional guard around that very line).

**Comment by brandomeniconi** [comment]
I've also disabled all Jetpack modules via WP CLI, included `publicize` but the error is still there.

**Comment by brandomeniconi** [comment]
I'm using our modified version of [_s](http://underscores.me/), but it hasn't any filters for Jetpack AFAIK.

I've tried to deactivate all plugins except for this ones:
```
+-------------+--------+--------+---------+
| name        | status | update | version |
+-------------+--------+--------+---------+
| gutenberg   | active | none   | 4.5.1   |
| jetpack     | active | none   | 6.8     |
| woocommerce | active | none   | 3.5.1   |
+-------------+--------+--------+---------+
```
error still shows up. 

The strange thing is that on two sites with the same plugins one is working now and the other don't. They both work ok if I switch back to Jetpack 6.7.

**Comment by brandomeniconi** [comment]
Tried to put the the Gutenberg-WooCommerce enable filter above in twentysixteen and enable it, still shows the error. Maybe you can try to install and configure 6.7 and then upgrade to 6.8. 

There is any way to purge all the Jetpack settings at once?

Reverting to 6.7 now, I can try to trace the bug myself tomorrow and give you some info back. It's a live site and I cant fiddle with it too much today, sorry.

**Comment by mookie44** [comment]
This error appeared for me on all of my woocommerce sites via the woocommerce API, error log is:

[Wed Nov 28 14:40:18.358055 2018] [proxy_fcgi:error] [pid 22795:tid 139969578342144] [client 127.0.0.1:50566] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Call to a member function current_user_can_access_publicize_data() on null in /wp-content/plugins/jetpack/_inc/lib/core-api/wpcom-fields/post-fields-publicize-connections.php:118\nStack trace:\n#0 /wp-content/plugins/jetpack/_inc/lib/core-api/wpcom-fields/post-fields-publicize-connections.php(136): WPCOM_REST_API_V2_Post_Publicize_Connections_Field->permission_check(17341)\n#1 /wp-content/plugins/jetpack/_inc/lib/core-api/class-wpcom-rest-field-controller.php(116): WPCOM_REST_API_V2_Post_Publicize_Connections_Field->get_permission_check(Array, Object(WP_REST_Request))\n#2 /wp-includes/rest-api/endpoints/class-wp-rest-controller.php(394): WPCOM_REST_API_V2_Field_Controller->get_for_response(Array, 'jetpack_publici...', Object(WP_REST_Request), 'product')\n#3 /wp-content/plugins/woocommerce/includes/api/v2/class-wc-rest-products-v2-controller.php(166): WP_REST_Controller->add_a...\n'

**Comment by jeherve** [comment]
@mookie44 I see you had also posted [in the forums](https://wordpress.org/support/topic/php-fatal-error-156/) and I replied there. Could you tell me more about your setup there, and try the suggestion I posted?

You also mentioned "via the woocommerce API"; could you tell me more about you get that error and how we could try to reproduce?

Thank you!

**Comment by mookie44** [comment]
@jeherve I've sent more details via the Jetpack contact form. Cheers!

**Comment by jeherve** [comment]
@mookie44 Did you get a ticket ID when you sent us the email? Could you let me know what it was?

**Comment by jeherve** [comment]
@ockham We have more information and steps to reproduce in #10743

**Comment by phamvietloi** [comment]
I am hosting my WooCommerce site on Pressable (managed-hosting) so they do not allow me to rollback Jetpack to 6.7 version. What should I do now? All of Products API do not work and business have to stop for over 2 days. Still need WooCommerce Service plugin so I can not disable Jetpack.

**Comment by jeherve** [comment]
@phamvietloi You can install [the Classic Editor plugin](https://wordpress.org/plugins/classic-editor/) on your site. Let me know if it helps!

**Comment by sirreal** [comment]
A summary of some investigation:

The offending line expects `global $publicize` to have a method `current_user_can_access_publicize_data`:
https://github.com/Automattic/jetpack/blob/62e6883ee0767f3cfbea1c32b07fce69dd32fce0/_inc/lib/core-api/wpcom-fields/post-fields-publicize-connections.php#L118

`global $publicize` appears to be set in the constructor for `Publicize_UI` here:
https://github.com/Automattic/jetpack/blob/35bd0be610333dd78c0b94ee4e88467cb0be3aa3/modules/publicize/ui.php#L18-L24

`Publicize_UI` seems to be instantiated here:
https://github.com/Automattic/jetpack/blob/35bd0be610333dd78c0b94ee4e88467cb0be3aa3/modules/publicize.php#L39
https://github.com/Automattic/jetpack/blob/35bd0be610333dd78c0b94ee4e88467cb0be3aa3/modules/publicize.php#L57-L58

So we would expect that if [`modules/publicize.php`](https://github.com/Automattic/jetpack/blob/35bd0be610333dd78c0b94ee4e88467cb0be3aa3/modules/publicize.php) were included, then `global $publicize; $publicize->current_user_can_access_publicize_data( $post_id )` would work just fine.

I'm not familiar with the intricacies of how modules are loaded, but it seems to me that the relevant files are not being included under some circumstances. I'd presume this is because the module is not active.

---

Following the instructions from #10743, I've verified that the REST API call mentioned there is broken when publicize is disabled. Enabling the publicize module fixes the problem. A temporary workaround for affected users may be to enable the publicize module:

From `/wp-admin/admin.php?page=jetpack#/sharing`, ensure _Publicize connections_ is enabled:

![publicize](https://user-images.githubusercontent.com/841763/49216235-dd819300-f3ca-11e8-9e8f-612ea399bd08.png)

---

Considering this, I think @jeherve's suggestion to guard this call in case `$publicize` is not instantiated is a good suggestion. I'll get a PR ready for that.

**Comment by sirreal** [comment]
A bit more detail, I was wondering _why_ we were hitting this publicize code path for a WooCommerce Rest API call.

WooCommerce declares `product` post type supports for `publicize`:

https://github.com/woocommerce/woocommerce/blob/83c71f053b2a4f25ce88243f9e68b0fff93aa307/includes/class-wc-post-types.php#L278

I believe the Rest API is attaching `jetpack_publicize_connections` fields to the products, which leads to this error:
https://github.com/Automattic/jetpack/blob/62e6883ee0767f3cfbea1c32b07fce69dd32fce0/_inc/lib/core-api/wpcom-fields/post-fields-publicize-connections.php#L36

> Considering this, I think @jeherve's suggestion to guard this call in case $publicize is not instantiated is a good suggestion. I'll get a PR ready for that.

I've rethought and I don't believe this is the best solution. It seems to me that, if the publicize module is not active, the `WPCOM_REST_API_V2_Post_Publicize_Connections_Field` API plugin should not even be loaded. I'd appreciate if someone could take a look at why this is API plugin is being loaded when the module is not active.

**Comment by tyxla** [comment]
Let's also cc @mdawaffe here.

**Comment by jeherve** [comment]
@phamvietloi Could you try to remove Publicize support for WooCommerce products, like so?

```php
function jeherve_rm_jetpack_publicize_woocommerce() {
    remove_post_type_support( 'product', 'publicize' );
}
 
add_action( 'init', 'jeherve_rm_jetpack_publicize_woocommerce' );
```

You can follow the instructions [here](https://jetpack.com/support/adding-code-snippets/) to add this code snippet to your site. Let me know how it goes.

**Comment by mookie44** [comment]
@jeherve Hey that worked! Just tried on one our websites. The woocommerce product API now works.

**Comment by timmyc** [comment]
FWIW another report in p90Yrv-TJ-p2 - @phamvietloi's solution of enabling publicize fixed it.

**Comment by fienen** [comment]
I can confirm that I've also encountered this same bug impacting the "Podcast" CPT created by the Seriously Simple Podcasting plugin.

**Comment by Trebacz** [comment]
Same bug seems to be affecting Ship Easy plugins ability to pull orders. Enabling publicize fixed it.

**Comment by htdat** [comment]
Another case with ShippingEasy 1617209-zen

**Comment by nyordanov** [comment]
@ockham I'm still getting the exact same fatal error with Jetpack 6.8.1 **when Jetpack is put in development mode using the `jetpack_development_mode` filter**.

It doesn't even have to be a WC product, this happens with the `jetpack-portfolio` CPT.

Changing the condition [on this line](https://github.com/Automattic/jetpack/blob/master/_inc/lib/core-api/wpcom-fields/post-fields-publicize-connections.php#L335) to `! Jetpack::is_development_mode() && Jetpack::is_module_active( 'publicize' )` does not fix the problem because the call to `add_filter( 'jetpack_development_mode', '__return_true' );` may not have happened yet if it is in a plugin. Try using the [Unplug Jetpack plugin](https://wordpress.org/plugins/unplug-jetpack/).

Is it possible to delay the above check until `init` or at least `plugins_loaded`?

**Comment by jeherve** [comment]
@nyordanov Could you tell us more about your setup? Publicize should not be active on a site running Development mode, since the feature requires a connection to WordPress.com. Is this for a site that was connected to WordPress.com before and used the Publicize feature, and where you then added the `jetpack_development_mode` filter?

**Comment by jeherve** [comment]
Thank you for the extra details.

Somewhat related: #1462 #3827

**Comment by bikedorkjon** [comment]
In 1687093-zen we've got a user reporting a similar issue using WP Ultimate Recipe Plugin.
