### ISSUE TITLE
Carousel: error thrown in `originalDimensions` function

### ISSUE THREAD

**Issue by keoshi** [Automattic/jetpack#11191]
#### Steps to reproduce the issue

1. Activate recommended features in Jetpack.
2. Create new post and add a 1) Tiled Gallery and 2) a Gallery block in Gutenberg.
3. Upload these [two](https://unsplash.com/photos/-SFhuMwFClk) [images](https://unsplash.com/photos/hDqLoCCGOdU). Add a long caption to the last one.
4. Publish post and click one of the images to display the carousel.

#### What I expected

- The clicked image to be displayed correctly in the carousel.

#### What happened instead

- Carousel came up empty (both the image, caption, exif data).
- Site is halted and clicks on the carousel don't work because of a JS error.
- Console shows this JS error:

```
Uncaught TypeError: Cannot read property 'split' of undefined
    at a.fn.init.originalDimensions (jetpack-carousel.min.js?ver=20190102:4)
    at a.fn.init.e.fn.jp_carousel (jetpack-carousel.min.js?ver=20190102:4)
```

![image](https://user-images.githubusercontent.com/390760/51674342-4733ad00-1fc8-11e9-88d3-aa4a4dd552ff.png)

Which seems to originate from the `originalDimensions` function:

https://github.com/Automattic/jetpack/blob/6189a00b72db562d5002b38ae87afce47c717591/modules/carousel/jetpack-carousel.js#L1067

**Screenshots**

![gallery-carousel](https://user-images.githubusercontent.com/390760/51674481-a691bd00-1fc8-11e9-845e-c06b98a955ba.gif)

**Comment by jeherve** [comment]
I can't seem to reproduce right now, with the same images.

![screen recording 2019-01-24 at 12 36 pm](https://user-images.githubusercontent.com/426388/51675702-c0390180-1fd4-11e9-944c-7bab8b9e8545.gif)

Was there any other plugin installed on the site? Can you reproduce with other images? Were there any issues when you uploaded the images?

**Comment by keoshi** [comment]
@jeherve No other plugins installed. The post I was testing this on had a tiled gallery on it as well, but that's it.

You can see it here: https://unaware-water-10.jurassic.ninja/2019/01/24/testing-carousel/

**Comment by keoshi** [comment]
And boom, site is gone. Did you manage to test it out before it went dark, @jeherve ? That's why I didn't add a link on it on the original issue.

**Comment by jeherve** [comment]
oh sorry, I was looking at another issue! :(

Can you reproduce with a brand new site now?

**Comment by keoshi** [comment]
No worries, @jeherve — will try to reproduce and report back.

**Comment by keoshi** [comment]
@jeherve Yep, managed to reproduce here: https://marxist-caribou.jurassic.ninja/2019/01/24/testing-galleries/

It seems the this error is only triggered when a simple gallery is used in tandem with a tiled gallery block. As you can see it doesn't happen with just the gallery block: https://marxist-caribou.jurassic.ninja/2019/01/24/testing-carousel-with-simple-gallery/

**Comment by jeherve** [comment]
Excellent, nice catch!

Related: #8033, #6638

**Comment by getdave** [comment]
So I've been looking into this as it's been causing issues (see `p58i-7RD-p2#comment-42220`). It turns out that we're missing a check for the `data-orig-size` attribute here:

https://github.com/Automattic/jetpack/blob/6189a00b72db562d5002b38ae87afce47c717591/modules/carousel/jetpack-carousel.js#L1205

This is causing a JS error to be thrown which causes the UI to freeze up.

This attribute appears to be added here

https://github.com/Automattic/jetpack/blob/master/modules/carousel/jetpack-carousel.php#L503

...which if you trace it back gets its data from a call to `wp_get_attachment_metadata()` here

https://github.com/Automattic/jetpack/blob/master/modules/carousel/jetpack-carousel.php#L455

However, if the image is not stored on the site there is no attachment. How can this happen? If you take a set of blocks and paste them into the editor (or insert them via code) then it's perfectly possible to have a gallery referencing images from another site.

So

1. We should add a check for `origSize` in the JS to avoid the crash.
2. Should/could we use a fall back set of dimensions?
3. How do we handle images that are not stored on the site directly?

**Comment by Silox** [comment]
Got the same problem [here](https://ambervallance.com/portfolio/black-and-white-illustrations/). Externally hosted images, the only one working in the carousel is the wider image at the bottom. Others don't show up and show the same Javascript error mentioned above.

**Comment by katiebethbrown** [comment]
Another report in #16986623-hc possibly related to externally hosted images.

**Comment by aheckler** [comment]
User in 2792313-zen gets this same error but does not seem to have externally hosted images.

**Comment by zdenys** [comment]
I noticed the same issue on https://docs.woocommerce.com/document/woocommerce-blocks/#section-2 where you can click any of the images in the gallery.

The only way I was able to reproduce it at this point in time is by adding a Gallery Block with one image, switching to Code Editor, and removing this set of 4 attributes for the `<img>` element (here is the [video](https://d.pr/v/X1Emg6)):

```
data-id="158" data-full-url="https://mystore123456789.wpcomstaging.com/wp-content/uploads/2020/09/Best-Selling-Products-Block-Settings-1.png" data-link="https://mystore123456789.wpcomstaging.com/?attachment_id=158" class="wp-image-158"
```

So possibly this has been somehow addressed in the latest versions of Gutenberg (which updated the Gallery Block)? I noticed that the issue is present when Gallery Block has no `Image size` section in the sidebar in the Editor. When that section is present (which is the case for any Gallery Block you add with the most recent version of Gutenberg), then the issue cannot be reproduced.

| Old Gallery Block  | Current Gallery Block |
| ------------- | ------------- |
| ![](https://d.pr/i/WvQaOJ+) | ![](https://d.pr/i/TiixSe+)  |

For Gallery Blocks added in the past, `<img>` didn't have the attributes `data-link` and `data-full-url`. Here's how a Gallery Block looks in the Code Editor when added today versus last year:

| Old Gallery Block  | Current Gallery Block |
| ------------- | ------------- |
| `<!-- wp:gallery {"ids":[945]} --><figure class="wp-block-gallery columns-1 is-cropped"><ul class="blocks-gallery-grid"><li class="blocks-gallery-item"><figure><img src="https://atrumtest03.files.wordpress.com/2019/10/wp-image-1419139768jpg.jpg?w=800" alt="" data-id="945" class="wp-image-945"/></figure></li></ul></figure><!-- /wp:gallery -->` | `<!-- wp:gallery {"ids":[158]} --><figure class="wp-block-gallery columns-1 is-cropped"><ul class="blocks-gallery-grid"><li class="blocks-gallery-item"><figure><img src="https://mystore123456789.wpcomstaging.com/wp-content/uploads/2020/09/Best-Selling-Products-Block-Settings-1-844x1024.png" alt="" data-id="158" data-full-url="https://mystore123456789.wpcomstaging.com/wp-content/uploads/2020/09/Best-Selling-Products-Block-Settings-1.png" data-link="https://mystore123456789.wpcomstaging.com/?attachment_id=158" class="wp-image-158"/></figure></li></ul></figure><!-- /wp:gallery -->`  |

I hope these bits help in any way.

**Comment by donalirl** [comment]
Encountered another case of this on a WP.com site in #24528170-hc / #3364177-zen

Recreated on this [test page](https://wpdoc20170704.wordpress.com/home/gallery-block/) by copying the code over.

Is there a workaround to get it working now, or any way to avoid this?

**Comment by eduardozulian** [comment]
Also reported in 23458609-hc

The workaround we used was to disable the slideshow in `admin.php?page=jetpack#/writing`. Not ideal, but it worked for this particular case.

**Comment by GeoJunkie** [comment]
Also seeing this on https://docs.woocommerce.com/document/log-into-woocommerce-com-with-wordpress-com/

**Comment by GeoJunkie** [comment]
An additional note on this one ^

The carousel was deactivated pending this bugfix, but when it's activated, it works fine if you're logged in to the site, but not if you're logged out.

**Comment by msilbers** [comment]
A customer reported this issue this week and I was able to reproduce it here:

https://melissasgutenbergteststuff.blog/gallery-variations/

The very first gallery image with the caption "lone gallery image"
Note that it is not a long caption and no externally hosted images.

I see this issue was reported in January, do we have any fix coming or a workaround? I notice this does not happen with the Tiled Gallery block.

**Comment by carladoria** [comment]
Another report in [25432752-hc](25432752-hc)
Disabling carousel fixed the issue

**Comment by bsanevans** [comment]
Another report in 3740078-zd-woothemes

**Comment by georgestephanis** [comment]
Just had this also happen to a friend of mine -- tracked down to this method:

https://github.com/Automattic/jetpack/blob/8924950d013b12041febe1d09316c592ba673a4b/projects/plugins/jetpack/modules/carousel/jetpack-carousel.js#L1216-L1219

and one other location (not specifically causing this error, but the same pattern) where it could cause an error where `orig-size` isn't specified:

https://github.com/Automattic/jetpack/blob/8924950d013b12041febe1d09316c592ba673a4b/projects/plugins/jetpack/modules/carousel/jetpack-carousel.js#L1342

In that file it looks like in other areas we're handling a lack of `orig-size` a couple places:

https://github.com/Automattic/jetpack/blob/8924950d013b12041febe1d09316c592ba673a4b/projects/plugins/jetpack/modules/carousel/jetpack-carousel.js#L1004

https://github.com/Automattic/jetpack/blob/8924950d013b12041febe1d09316c592ba673a4b/projects/plugins/jetpack/modules/carousel/jetpack-carousel.js#L1042

Idea resolution should (in my opinion) be two-fold:

1) Find cases where `orig-size` isn't added to the src (this seemed to be in a gallery block), and see if we can filter it to add that data attribute in as well,
2) Make the js more resilient so it has some sort of fallback code path if `orig-size` isn't available.

**Comment by Nic-Sevic** [comment]
another report here: 3998202-zen

also showing the error specifically on the first method mentioned above if it helps

during testing I found this only happened when polylang was activated as well

**Comment by msilbers** [comment]
Customer report again in 29766232-hc

**Comment by al3xstanhope** [comment]
So sorry to be the bearer of bad tidings, guys! Sadly, it looks like this is still an issue in the latest version of Jetpack; we have a carousel set up on a client's site and are experiencing the same problems as noted in the original report.

The images in the gallery are hosted on the Photon CDN for what it's worth!

Any thoughts on when a fix might be inbound?

**Comment by jeherve** [comment]
> Any thoughts on when a fix might be inbound?

We do not have a fix merged yet, but we'll update this issue as soon as we make progress on this.

**Comment by goblinartificer** [comment]
I had a user experience this today ⁠—the issue happened upon importing the posts from a previous site. The original posts are from 2011. On the exported site, the image size option is available in the sidebar in the editor; on the newer one, it is not. The console errors look similar. Both sites are simple Free sites.

They're exactly the same post, imported over. On the new site, the carousel shows blanks or stretched/distorted (aspect ratio) images, depending on the post; when "view full size" is clicked, entirely incorrect images load. 

I see that #20010 has been merged into WordPress.com this week, but this is happening on an import that was made within the last 48 hours, so it seems like something else is still unresolved.

Reopening, let me know if you need any further information!

original Slack thread with a video link and sample posts from both sites here: p1623885670301900-slack-C03TY6J1A

just for completeness, 4074134-zen 28227606-hc

**Comment by sgomes** [comment]
Thank you, @goblinartificer, I'll look into this 👍

**Comment by sgomes** [comment]
It looks like the failing images don't include a `data-attachment-id` property, and only include `data-id`.

@jeherve : Do you know more about these properties? Should we treat `data-id` as equivalent to `data-attachment-id`?

**Comment by sgomes** [comment]
I have a fix that I can turn into a PR, and will make the carousel work with these images, if we consider that `data-id` should indeed be used when `data-attachment-id` is not available.

Of course, this is just a partial fix, so that things don't break. The images will be tiny in the carousel (same size in the as they are in the gallery), since we don't have any info of what their original size is. There's not much we can do about that given the extremely limited markup that the blocks gallery is giving us.

I'm not sure how to get the blocks gallery to fill in the extra info, so that the images can be displayed at a larger size. Perhaps opening the post in Gutenberg and fixing any errors would do the trick?

**Comment by goblinartificer** [comment]
If it helps any, we have permission from that user to make minor changes to their site at any point while figuring things out. If you'd like me to go in and see if editing and fixing will work at a later point, or ask the user to do so, we can make that happen. Thank you for your hard work!

**Comment by sgomes** [comment]
Thank you, @goblinartificer!

This should now be fixed on wpcom! 🙂 It looks like the test site I was using was changed to the Gutenberg slideshow, however, so I can't directly test.

**Comment by msilbers** [comment]
@sgomes I checked my old test page for this: https://melissasgutenbergteststuff.blog/gallery-variations/#jp-carousel-63

I no longer see the same errors in console, but the issue persists
We also had a report of this in https://github.com/Automattic/wp-calypso/issues/53882

Should this be a new issue if the errors are different? Seems like the exact same problem visually, and I spot-checked a few reports above and found this unfixed, including:

> another report here: 3998202-zen

**Comment by goblinartificer** [comment]
@msilbers I forgot to post here, but it's still persistent even on the case I reported earlier ⁠— Slack post: p1624337699095100-slack-C03TY6J1A?thread_ts=1623885670.301900&cid=C03TY6J1A

**Comment by sgomes** [comment]
Thank you, @msilbers! It looks like the images in your gallery are yet another variation in how data can go missing. I'll try to account for those as well 👍

**Comment by sgomes** [comment]
The issue appears to be that there are situations where images contain absolutely no width and height information in the markup. This makes it impossible for us to display them in the current setup.

@jeherve : what do you think we should do here? The only solution I see is to preload all of the images that don't have sizing info, so that we can know their size ahead of opening the carousel. Do you think that's acceptable?

**Comment by jeherve** [comment]
Would it be acceptable / possible to not trigger any Carousel modal for such images? If width and height is missing, I assume there was a problem during upload. This may happen on posts with lots of big images, maybe, in which case we wouldn't want to start pre-loading images on such posts since that would potentially be a lot of images.

**Comment by sgomes** [comment]
The issue is that some versions of Gutenberg generated galleries without sizing info, which is what happened here. The upload worked well and the images exist in a good state, but the gallery is simply missing the info.

I think we have one last option that doesn't involve preloading, which is to use the thumbnail natural size; we already measure that, so we can just display the tiny gallery image in the carousel, as we're already doing in other cases. I'll give that a try.

**Comment by sgomes** [comment]
Using the thumbnail natural size appears to work. Created #20149 with the fix.

**Comment by sgomes** [comment]
Both the test cases from @msilbers and @goblinartificer appear to be working well with the latest fix! 🙂

As such, I'm closing this issue again, but please do reopen it if you find any other cases! We'll get rid of all of those edge cases yet! 😄

**Comment by jeherve** [comment]
The problem seems to happen on this site, whether they run Jetpack 9.8.1 or Jetpack 9.9:
https://ayudawp.com/optimizar-slider-revolution/

I am not sure why this happens there, though I do note that they use WP Rocket and its defer JS feature. That said, the reporter mentioned that excluding the Carousel's script from being defered does not appear to solve the issue.

Reference: 
https://wordpress.org/support/topic/cannot-read-property-split-of-undefined-at-jetpack-carousel-min-js/

**Comment by sgomes** [comment]
@jeherve : thanks for the link! It looks like that's a separate issue. The carousel doesn't behave two well when there are exactly two slides, apparently. I'll look into it.

**Comment by sgomes** [comment]
> @jeherve : thanks for the link! It looks like that's a separate issue. The carousel doesn't behave too well when there are exactly two slides, apparently. I'll look into it.

Update: I'm not able to test things with this exact site, but I implemented a 2-slide carousel (using the carousel in `master`) on my test site and it seems to work correctly. Perhaps the use of swiper ended up fixing the issue?

**Comment by jeherve** [comment]
> Perhaps the use of swiper ended up fixing the issue?

It would appear that it didn't on that specific site; the owner experiences the same issue when updating to 9.9. 

I cannot reproduce the problem on my end, though. :\

@fernandotellado Would you be able to copy the HTML you have in the editor for that post, and send it to us, either in a [Gist](https://gist.github.com/) or privately [via our contact form](https://jetpack.com/contact-support/?rel=support&hpi=1)?

Thank you!

**Comment by fernandotellado** [comment]
> > Perhaps the use of swiper ended up fixing the issue?
> 
> It would appear that it didn't on that specific site; the owner experiences the same issue when updating to 9.9.
> 
> I cannot reproduce the problem on my end, though. :\
> 
> @fernandotellado Would you be able to copy the HTML you have in the editor for that post, and send it to us, either in a [Gist](https://gist.github.com/) or privately [via our contact form](https://jetpack.com/contact-support/?rel=support&hpi=1)?
> 
> Thank you!

Of course, here it is: https://github.com/fernandotellado/fernandotellado/blob/master/jetpack-9-9-issue

**Comment by jeherve** [comment]
Thank you! Any chance you could copy from the HTML view in the editor as well, like so?


https://user-images.githubusercontent.com/426388/124786401-f883ee80-df47-11eb-8d11-c15fd0618a33.mov

**Comment by fernandotellado** [comment]
Ah, of course, here it is: https://github.com/fernandotellado/fernandotellado/blob/master/html-post-slider

I can even give you admin access to the site if you want to make the test by yourself ;)

**Comment by kerrynicl** [comment]
Hi Team, I see the issue is still occurring on this [site ](https://octaviasparker.com/portfolio/oulawa-selected-works-pt1/) When a picture is selected I get a black screen and the page becomes unresponsive.

**Comment by sgomes** [comment]
Thank you, @kerrynicl !

This is the most extreme case of missing info I've seen so far 😕 In this case, the attachment ID property is present but empty, so there isn't anything meaningful we can do with the image.

The only reasonable course of action in these situations is probably to simply refuse opening the carousel. @jeherve, what do you think?

**Comment by sdixon194** [comment]
@sgomes Jeremy is AFK for a bit, but I did some extensive testing and definitely seems something is up with the images. Trying to do some testing and they are being saved as webp images? I'm not sure what's up with that.

@kerrynicl I think I would have them try and re-upload the images, or download them and re-upload them and see if that fixes things. Are they able to use the carousel with other images/galleries, or does it happen for all of them? Or, like Sergio suggested, try disabling the carousel.

**Comment by Thelmachido** [comment]
On this [site](https://articoliliberi.com/) we have a [Post Carousel block](https://wordpress.com/support/wordpress-editor/blocks/posts-carousel-block/) and the site is on a WordPress.com theme. With autoplay disabled, if you try to view the next post using the [swiper arrow icons on the side of the image](https://d.pr/i/u0SMxq) some of the featured images are black but if you use the [swiper bullets on the bottom](https://d.pr/i/URv1Na) of the carousel the images aren't affected as shown [in this video](https://d.pr/v/KLBgSm)

**Comment by jeherve** [comment]
@Thelmachido I'm afraid you're running into a different problem entirely. This issue is for the Carousel feature, triggered when opening gallery images. You seem to be having issues with the Post Carousel block, a block that's developed and maintained in [this repo](https://github.com/Automattic/newspack-blocks/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22%5BBlock%5D+Carousel%22). I would recommend opening an issue there directly.

********

**Note**: When you create that new issue, I would encourage you to upload your screenshots and screencasts to GitHub directly instead of using Droplr. See this for more info:
pbg9X-fWF-p2

**Comment by Thelmachido** [comment]
> @Thelmachido I'm afraid you're running into a different problem entirely. This issue is for the Carousel feature, triggered when opening gallery images. You seem to be having issues with the Post Carousel block, a block that's developed and maintained in [this repo](https://github.com/Automattic/newspack-blocks/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22%5BBlock%5D+Carousel%22). I would recommend opening an issue there directly.
> 
> **Note**: When you create that new issue, I would encourage you to upload your screenshots and screencasts to GitHub directly instead of using Droplr. See this for more info: pbg9X-fWF-p2

Thanks I will remove the above comment, to avoid confusion.

**Comment by kelasante** [comment]
Got a chat in 35760928-hc where Images in Carousel are black when you click on images in Gallery block. I see this when I inspect:

<img width="1399" alt="Markup 2022-06-10 at 16 28 54" src="https://user-images.githubusercontent.com/74204272/173158650-2e23ae17-b4d1-4ea1-b1d6-b6bcc7e742ee.png">


However, I took a look at the image URL and it looks something like https://import.files.wordpress.com/abc. User mentioned they just imported from Wix so in this case, the issue seems to be with the import file so uploading the file directly should fix it but commenting here just in case it is related to this issue.
