### ISSUE TITLE
Carousel shows photo caption for gallery shortcode photos but not gallery block photos

### ISSUE THREAD

**Issue by Praful** [Automattic/jetpack#11594]
The carousel shows a photo's caption if the photo was added to a post from a gallery shortcode. It does not appear if added via a gallery block.

There is another issue logged ([#9237](https://github.com/Automattic/jetpack/issues/9237)) but this is for tiled galleries. My issue is for plain gallery blocks.

#### Steps to reproduce the issue

1. Create a post.
2. Add a gallery block.
3. Add three photos giving each a caption.
4. Save the post.
5. Enable Jetpack Setting > Writing > Display images in a full-screen carousel gallery
5. View the post.
6. Click a photo in the post to view the photos via the carousel.
7. The caption you entered in step 3 does not appear.

#### What I expected

I expected the caption for the photo to be shown beneath the photo.

A caption *is* displayed if you enter photos into the post using the gallery shortcode, eg like this:

```
[gallery columns="3" size="large" ids="7091,7083,7085"]
```

#### What happened instead

No caption is visible for photos in a gallery block.

**Screenshots**

Here are some links from my blog:

- An example of [captions *not* being shown](https://prafulkapadia.com/2019/03/14/highgate-cemetery/). This used a gallery code.
- An example of [captions being shown](https://prafulkapadia.com/albums/india-varanasi-and-delhi/). This uses a plain gallery block.

**Comment by jeherve** [comment]
This stems from the way the block editor handles image metadata. 

- In the classic editor or the classic block, when you edit an image (and add an alt or caption text for example), an image modal appears and the changes you make in that modal are saved as the image's metadata. If later on you try to add the same image to another post or another gallery, you'll get the same alt and caption you had saved before. Similarly, if you search for that image under Media > Library in your dashboard, you'll see the caption you had saved there.
- In the block editor, however, if you add an alt or a caption to an image it is not saved as the new image metadata; it is only saved in the post content. If you insert that same image in another post, you will have to specify an alt and a caption again.

This is problematic for plugins and themes (like Jetpack) that rely on image metadata, and may not be the best solution for all site owners. It does, however, have the advantage to allow folks to insert the same image in different posts with different captions.

This behaviour of the block editor may change in the future, as it is being discussed here:
https://github.com/WordPress/gutenberg/issues/8941
https://github.com/WordPress/gutenberg/issues/13642
https://github.com/WordPress/gutenberg/issues/12913

Until then, or if WordPress Core decides not to change things, I think it would make sense for Jetpack's Carousel to support that custom behaviour of the block editor.

**Comment by Praful** [comment]
@jeherve  thanks for the explanation. I'm new to WordPress. I'm curious how this works under the covers - why one gallery works and another doesn't.

So far I've seen gallery shortcuts, gallery blocks and tiled gallery blocks. It seems obvious to have a base object that they reduce to before that base object is rendered to HTML/CSS/JS. This avoids multiple conversions from what the user enters in the editor and what appears in the browser.

My assumption was that they all reduce to a gallery shortcode, since it takes various properties and it could easily be extended eg `type="tiled", caption="first caption,,third caption"` and so on.

You could still have central captions for images and override them in the gallery shortcode so that, if not present, the caption with the image is used otherwise the caption in the gallery shortcode is used.

**Comment by katiebethbrown** [comment]
Another report of this in #21957956-hc.

**Comment by jordesign** [comment]
Another instance of this in #3577920-zen

@jeherve is it safe to say that this is a situation of won't/can't fix ?
I've suggested using the shortcode as an alternative in this instance.

**Comment by jeherve** [comment]
> is it safe to say that this is a situation of won't/can't fix ?

Yes, that may be fair at this point. 👍

We can always reopen in the future if needed.

**Comment by alpopp** [comment]
Hi @jeherve, is this getting fixed in [#20300](https://github.com/Automattic/jetpack/pull/20300)?

**Comment by jeherve** [comment]
@alpopp No, that PR will not change the situation. Unfortunately the underlying problem I described in https://github.com/Automattic/jetpack/issues/11594#issuecomment-474273664 is still the same.
