### ISSUE TITLE
Gutenberg: "Jetpack" icon/logo not in toolbar for Pages

### ISSUE THREAD

**Issue by mzakariya** [Automattic/jetpack#12228]
#### Steps to reproduce the issue

1. Edit a **Page** using Gutenberg

#### What I expected

2. The Jetpack icon is in the toolbar, which is how you'd access features like Publicize or wp.me shortlinks
    - https://jetpack.com/support/wp-me-shortlinks/

#### What happened instead

3. The icon isn't available, so these features aren't accessible on Pages

**Screenshots**

![](https://cld.wthms.co/SnF3QD+)
Image Link: https://cld.wthms.co/SnF3QD

**Comment by jeherve** [comment]
This was fixed in #12210

**Comment by scosgro** [comment]
> This was fixed in #12210

@jeherve 
User on WordPress.com Atomic site is still having this issue. Tested on their site and a personal AT site and replicated on both. Jetpack icon only appears on Posts, does not appear on Pages. 

Shortlink options are unavailable. When searched, there is no option to enable them:

![Untitled](https://user-images.githubusercontent.com/30731356/57157267-187e5d00-6d95-11e9-872f-375db09ba090.png)
https://cloudup.com/c2wlGofUFFQ

![Untitled2](https://user-images.githubusercontent.com/30731356/57157279-246a1f00-6d95-11e9-8ceb-49cb9c8efdc7.png)
https://cloudup.com/cU7utKA9EN3

**Comment by jeherve** [comment]
@scosgro The fix is only in the development version of Jetpack. It will be made available to all Jetpack site owners tomorrow, as Jetpack 7.3 gets released.

> Shortlink options are unavailable. When searched, there is no option to enable them:

When you do not see any "Activate" button next to a feature like on your screenshots, it means that the feature is already active. You can confirm that by heading to the full module list:
`http://yoursite.com/wp-admin/admin.php?page=jetpack_modules`
