### ISSUE TITLE
Stats: RTL languages - x-asis shows inconsistent date info 

### ISSUE THREAD

**Issue by htdat** [Automattic/jetpack#13440]
#### Steps to reproduce the issue

1. Change site to a RTL language like Hebrew. 
2. Visit wp-admin/admin.php?page=jetpack#/dashboard
3. X-Asis does not display the consistent info when hovering on a specific day. 

In the screenshot below, when selecting a day on September, the tooltip shows August: 

![Screen Shot on 2019-09-06 at 16:23:27](https://user-images.githubusercontent.com/10045087/64417608-a1026680-d0c3-11e9-903f-b44abf601328.png)

**Comment by jeherve** [comment]
Also worth noting that none of the numbers on the axis are translated. We may have to look into `moment` to understand what's happening here:
https://github.com/Automattic/jetpack/blob/fe5b739531bba42eb7fc5724471410694cea9781/_inc/client/at-a-glance/stats/index.jsx#L72

**Comment by jeherve** [comment]
This should be fixed as of #17343 and #17357.

**Comment by htdat** [comment]
Re-opening this issue.
The issue is still there in Jetpack 9.1. I can replicate it. 
Another report https://wordpress.org/support/topic/chart-in-arabic-in-wring-direction/

**Comment by jeherve** [comment]
This should now be fixed with the new version of the Stats page.
