### ISSUE TITLE
Placing Jetpack in mu-plugins causes Network Admin to report incorrectly

### ISSUE THREAD

**Issue by jeremeylduvall** [Automattic/jetpack#13478]
On the Network Sites page, Jetpack has a check here that looks to see if the Jetpack plugin is active:

https://github.com/Automattic/jetpack/blob/master/class.jetpack-network-sites-list-table.php#L82

An issue presents itself then if Jetpack is in the mu-plugins directory as it is on all VIP Go sites. This leads to a confusing experience because pages like this:

example.com/wp-admin/network/admin.php?page=jetpack

Will read Jetpack is not active on this site. under "Connected" despite the site actually being correctly connected and Jetpack being active.

@kraftbj suggested one possible approach:

> For the Jetpack network admin, we could add a check || array_keys( get_mu_plugins(), 'jetpack.php', true (need to check what the key is right, jetpack.php or mu-plugins/jetpack.php, etc) to match what is returned and match what VIP Go uses. It may be cleaner for us to add a filter there since any mu-plugin-loaded Jetpack network would have to be custom on some level.

This has come up with several VIP clients, and I imagine others that use a similar `mu-plugins` approach.

**Comment by kraftbj** [comment]
Fixed a similar issue in #15493 for the installs managed by the beta plugin.

**Comment by mattoperry** [comment]
This issue is still affecting multiple VIP clients. If @kraftbj did solve a substantially similar in #15493, could we extend that solution to fix this issue?
