### ISSUE TITLE
Double “Read More” link in subscription email

### ISSUE THREAD

**Issue by andrewdawson11** [Automattic/jetpack#15447]
“Double “read more” link in subscription email.”

#### Steps to reproduce the issue

1. Use WordPress 2016 theme and make sure it’s up to date with their latest version.
2. Have Jetpack email subscribers to blog and email subscriptions turned on and that the email should only have an excerpt, not full text.
3. Post a blog with enough text to show the excerpt email.
4. Receive email to see the double link.

This issue appeared after the latest update to the WordPress 2016 theme came from them. 

#### What I expected

There should only be one read more link in the email. I only have the excerpt feature turned on.

#### What happened instead

![7079862C-BC77-4393-9D4F-1BA7AE519274](https://user-images.githubusercontent.com/63666358/79256565-3df56100-7e56-11ea-9381-df5245c33c73.png)

**Comment by jeherve** [comment]
Related: #7178

This seems to be a regression.

**Comment by andrewdawson11** [comment]
What does it mean to be that it’s a regression?

**Comment by supernovia** [comment]
I've got another instance here:
https://wordpress.com/forums/topic/email-template-2/

Regression meaning it was fixed then reintroduced somehow.

**Comment by htdat** [comment]
Note that this issue happens to WP.com (simple) sites too!

**Comment by jeherve** [comment]
This issue has now been fixed.

**Comment by danjjohnson** [comment]
This appears to have regressed again. I can reproduce using the Twenty Twenty One theme:

![image](https://user-images.githubusercontent.com/1990037/119327617-112b9400-bc7b-11eb-8b38-0f02ca190133.png)

**Comment by jeherve** [comment]
@danjjohnson It should be fixed again, with the same fix as last time (see reference above).

**Comment by bobmatyas** [comment]
@jeherve This issue is back with the same circumstances causing it.

**Comment by jeherve** [comment]
Internal reference: p7H4VZ-3eR-p2

**Comment by kraftbj** [comment]
Let's try again. This seems to be an after-effect of the fix for PBE detailed in p58i-bqt-p2. 

I changed this up to something less problematic per p7H4VZ-3eR-p2#comment-10011
