### ISSUE TITLE
Protect and Varnish: Potential Security Violations

### ISSUE THREAD

**Issue by edsu** [Automattic/jetpack#1966]
Protect is suddenly locking everyone out from access wp-admin with this error:

    Your IP (206.196.184.38) has been flagged for potential security violations.

This is the IP address that I'm accessing the Internet from. We are running Wordpress on one machine behind a Varnish proxy on another machine. It does appear that we have seen some attempts to login in from unexpected places in the Ukraine. Is it possible that Protect is identifying all traffic as a potential security violation because it is all coming from Varnish? 

Any help/pointers you can provide would be appreciated. I have been able to login to admin by manually adding my IP address to the wp_config.php. But I would like to know if Jetpack Protect can flag malicious traffic without blocking everyone out while we use Varnish.

**Comment by dereksmart** [comment]
You're correct, this happens when a site is using a firewall/cache box and so the protect API servers are seeing all traffic coming to that site as having the same IP.

It was a side effect of a recent change (a much more restrictive manner of trusting IP headers).  Regardless, we are currently working on finding and implementing a workaround to this specific problem, so thank you for the report -

**Comment by tristanleboss** [comment]
I find strange that we are only 2 persons to report this bug. Tons of WordPress installations run on server using Varnish. Maybe there is something with our specific configuration/version of Varnish?

If it can help: I use varnish v3.0.2 revision 55e70a4 under Debian GNU/Linux 7.8 (wheezy) up-to-date. Apache use 127.0.0.1:80 and Varnish use the external_server_IP:80.

_SERVER["REMOTE_ADDR"]	127.0.0.1
_SERVER["SERVER_PORT"]	80
_SERVER["SERVER_ADDR"]	127.0.0.1
_SERVER["HTTP_X_FORWARDED_FOR"]	90.53.123.178

**Comment by samhotchkiss** [comment]
We've had a handful of reports, it's definitely a high priority, and should be resolved within the next week or so

**Comment by edsu** [comment]
I wonder if the situation is specifically when the Varnish server is running on a separate machine than the Apache instance serving up Wordpress?

**Comment by tristanleboss** [comment]
I don't think so because my Varnish and Apache server are on the same machine and I still experience this problem...

**Comment by edsu** [comment]
Yes, I did mean different IPs.

**Comment by tedd** [comment]
Having the same issue. Would be great if I could give the proxy server IP(s) to Protect and if requests came from this then it read client IP from HTTP header instead. (Note that some people may have multiple proxy server IP's because of NLB.)

The reason why I want to specify the proxy IP in Protect is because of security concerns. If my WP is (or by accident becomes) available outside of the proxy then a hacker could easily figure it out (probe nearby IP's for HTTP that answers to hostname). HTTP headers could then be used to bypass Protect.

**Comment by ctalkington** [comment]
seeing this quite often on client sites since upgrading to plesk 12.5 with nginx 1.9 sitting in front of apache 2.4 (reverse proxy)

**Comment by ctalkington** [comment]
a bit more detail:

the nginx reverse proxy adds the proper forwarded headers and `trusted_ip_header` is `HTTP_X_FORWARDED_FOR` which has proper user IP.

however the response it appears to be saving to transient ls the server ip, yet the error message lists out correct user IP.

**Comment by samhotchkiss** [comment]
Hi Chris-- there is currently an issue with the Protect Server not being
trusting enough with the trusted_ip_header-- a fix is in the works and
should be live within the next week

**Comment by ctalkington** [comment]
@samhotchkiss thanks, i think the main culprit of it suddenly having issues on these plesk servers was that apache was upgraded to 2.4 but `mod_remoteip` wasn't enabled to take `mod_rpaf` place.

**Comment by edsu** [comment]
Can someone summarize why this issue was closed?

**Comment by tedd** [comment]
I think it was closed because what we wanted solved should be fixed by Apaches mod_remoteip and IIS's ARR + ARR Helper Module http://blogs.iis.net/anilr/client-ip-not-logged-on-content-server-when-using-arr .... Not by Wordpress. So the problem is a network infrastructure problem, not a Wordpress problem.

**Comment by edsu** [comment]
What is the Apache solution?

**Comment by tedd** [comment]
mod.remoteip for Apache 2.3 and higher, not sure what it was before.
https://httpd.apache.org/docs/trunk/mod/mod_remoteip.html

See http://serverfault.com/questions/616422/apache-mod-remoteip-and-access-logs for example.
In short you enable mod_remoteip and add (if proxy ip is within 192.168.0.*):
RemoteIPHeader X-Forwarded-For
RemoteIPInternalProxy 192.168.0.0/24

**Comment by edsu** [comment]
Thanks!
