### ISSUE TITLE
Sync: PHP warning in Sync Sender

### ISSUE THREAD

**Issue by simkoG** [Automattic/jetpack#20552]
#### Steps to reproduce the issue

1. Open Apache log file 
2. There are a plenty lines of PHP Warning which refer to the  `class-sender.php` file. 

#### What I expected

No PHP warning in the log. 

#### What happened instead

`[04-Aug-2021 07:03:53 UTC] PHP Warning:  strlen() expects parameter 1 to be string, array given in /{wp_install_folder}/wp-content/plugins/jetpack/vendor/automattic/jetpack-sync/src/class-sender.php on line 440`

**Comment by jeherve** [comment]
Could you try to update to the most recent version of the Jetpack plugin? In Jetpack 10.0 we included #20444, which should fix the warnings you're seeing.

Thank you!

**Comment by danjjohnson** [comment]
@jeherve we got another report [here](https://wordpress.org/support/topic/error-of-type-e_error-was-caused-in-line-440/#post-14733837) that the errors are still occurring in Jetpack 10.0

**Comment by jeherve** [comment]
Hm. I assume the line numbers are now different. Could you ask the reporter for a fresh error from their logs?

**Comment by danjjohnson** [comment]
@jeherve from the forum post:

> I haven’t gotten the e-mail yet again. However, the result that I see when attempting to use the ‘Customize’ tools in the Appearance tab (for instance ‘Widgets’) are the same as I was getting before. Deactivating Jetpack clears up the errors. So, when I go to ‘Customize’ or ‘Widgets’ I see:

```
Warning: Undefined property: stdClass::$post_status in /home/gerenm/www/www/wp-admin/includes/misc.php on line 1433

Warning: Undefined property: stdClass::$post_status in /home/gerenm/www/www/wp-admin/includes/misc.php on line 1433

Warning: Undefined property: stdClass::$post_status in /home/gerenm/www/www/wp-admin/includes/misc.php on line 1433

Warning: Undefined property: stdClass::$post_status in /home/gerenm/www/www/wp-admin/includes/misc.php on line 1433

Warning: Undefined property: stdClass::$post_status in /home/gerenm/www/www/wp-admin/includes/misc.php on line 1433

Warning: Undefined property: stdClass::$post_status in /home/gerenm/www/www/wp-admin/includes/misc.php on line 1433

Warning: Undefined property: stdClass::$post_status in /home/gerenm/www/www/wp-admin/includes/misc.php on line 1433

Warning: Undefined property: stdClass::$post_status in /home/gerenm/www/www/wp-admin/includes/misc.php on line 1433

Warning: Undefined property: stdClass::$post_status in /home/gerenm/www/www/wp-admin/includes/misc.php on line 1433

Warning: Undefined property: stdClass::$post_status in /home/gerenm/www/www/wp-admin/includes/misc.php on line 1433

Warning: Undefined property: stdClass::$post_status in /home/gerenm/www/www/wp-admin/includes/misc.php on line 1433

Warning: Undefined property: stdClass::$post_status in /home/gerenm/www/www/wp-admin/includes/misc.php on line 1433

Warning: Undefined property: stdClass::$post_status in /home/gerenm/www/www/wp-admin/includes/misc.php on line 1433

Warning: Cannot modify header information - headers already sent by (output started at /home/gerenm/www/www/wp-admin/includes/misc.php:1433) in /home/gerenm/www/www/wp-admin/customize.php on line 126
```

> Note that in the very last line, the final line number may vary, depending upon the customize option I choose. Appearance=>Customize throws line 126, Appearace=>Widgets throws line 9, for instance.

**Comment by jeherve** [comment]
That seems to be a different error, currently tracked in #18616. I'll close this issue since the problem here has been fixed, and the other problem is already tracked there.
