### ISSUE TITLE
Sites using https with CloudFlare have xmlrpc for jetpack blocked

### ISSUE THREAD

**Issue by virendrachandak** [Automattic/jetpack#2265]
This is an old issue (and probably not bug with Jetpack) for which I have contacted both CloudFlare and Jetpack support teams and seems it is still not resolved, so I just wanted to create it here, so that it is easier to track and also other users can be aware of this issue.

When you try to access https://<blog_URL>/xmlrpc.php?for=jetpack CloudFlare blocks it. I think this is the reason the site cannot cannot be managed from wordpress.com.

After communicating with CloudFlare support team they say this has been blocked on their end (https://blog.cloudflare.com/our-waf-is-keeping-wordpress-jetpack-on-track/) and cannot be disabled even by custom page rules. They say that as a work around to this you can use HTTP to make the request without getting blocked: http://<blog_URL>/xmlrpc.php?for=jetpack. However, I don't think this is possible with Jetpack.

So, if you have https enabled on your site using CloudFlare, then CloudFlare blocks access to the /xmlrpc.php?for=jetpack and hence the site cannot be managed from wordpress.com and also there are a few errors in the wp-admin for things like publicize. 

I am not sure how this issue can be fixed. If this cannot be fixed, may be it should be add to the list of Known issues (http://jetpack.me/support/getting-started-with-jetpack/known-issues/)

Hopefully you guys can work with CloudFlare to try to get this issue resolved, since I am sure many other sites might be facing the same issue.

**Comment by kraftbj** [comment]
Howdy,

This isn't universally true and is somewhat dependent on your CloudFlare settings. My test site using CloudFlare, while blocking my own attempts to visit /xmlrpc.php?for=jetpack on my IP address fails, communication from Jetpack's servers are allowed through.

Alternatively, you can whitelist IPs that "violate" their rule via the Traffic Control section of the CloudFlare control panel. That'll display violations they've enforced.

**Comment by kraftbj** [comment]
Though, notable, you may need to add `$_SERVER['SERVER_PORT'] = 443;` to your wp-config.php if your site is promoting itself as https.

**Comment by ddmboss** [comment]
I had this exact same problem a while back, the $_SERVER fix you recommended fixed it, maybe you guys should add it to the support pages

**Comment by jeherve** [comment]
> maybe you guys should add it to the support pages

I've just edited one of our support pages to include that recommendation. Thanks!

**Comment by MrGravgaard** [comment]
In CloudFlare you need to disable rule ID WP0007

Firewall -> Web Application Firewall -> Rule Details -> Advanced

Then You search for ID WP0007 - and disable it. 

![image](https://cloud.githubusercontent.com/assets/16425360/25555543/85329874-2ce9-11e7-99ec-6e7f19b7942a.png)

**Comment by virendrachandak** [comment]
To disable the rule we need a Cloudflare pro plan. On free plan you cannot do that.

**Comment by jeherve** [comment]
@virendrachandak CloudFlare does not block your site from communicating with WordPress.com when using the free plan. If you experience issues connecting your site to WordPress.com, the problem is not caused by CloudFlare. If you'd like us to take a look at your site, don't hesitate to contact us via [this form](https://jetpack.com/contact-support/)!

**Comment by virendrachandak** [comment]
I cannot reproduce the issues anymore. Seems the issues have been fixed over the past 2 years (when the issue was originally reported), jetpack now works fine even with Cloudflare enabled.

**Comment by bozj** [comment]
No. It is not working. WP.com doesn't sync my website.

**Comment by MrGravgaard** [comment]
I agree. The issue is still there. 

Best regards,
Chrstian Gravgaard
https://christian-gravgaard.com/

**Comment by jeherve** [comment]
@bozj @MrGravgaard If you experience issues when trying to connect Jetpack to your WordPress.com account, the problem is most likely not caused by CloudFlare, as CloudFlare does not block XML-RPC requests coming from WordPress.com by default.

If you would like us to take a closer look and help you figure out what's blocking the requests on your site, can you please use Jetpack's Debugger module to send us some more information about your sites?

<ol>
<li>Go to the Jetpack page in your dashboard.</li>
<li>Click on the <strong>Debug</strong> link appearing at the bottom of the page.</li>
<li>Click the link that says <strong>"click here to contact Jetpack support."</strong></li>
<li>Fill in the description box and your name and email address.</li>
<li>Click the "Contact Support" button to send us the debug results privately. <strong>It's best not to post this information here, as it contains private details about your site.</strong></li>
</ol>

Thanks!
