### ISSUE TITLE
Odyssey Stats: Days/Weeks/Months/Years filters are not functional

### ISSUE THREAD

**Issue by brbrr** [Automattic/jetpack#28142]
### Impacted plugin

Jetpack

### Steps to Reproduce

1. Make sure new stats is enabled
2. Visit `/wp-admin/admin.php?page=stats`
3. Click on one of the filters (days/weeks etc)
4. Observe how nothing is reacting to your clicks

### A clear and concise description of what you expected to happen.

Behavior identical to the one in WPCOM

### What actually happened

Nothing 🙈 

### Browser

Google Chrome/Chromium

### Platform (Simple, Atomic, or both?)

Atomic, Self-hosted

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

None

**Comment by jsnmoon** [comment]
This should be addressed via #28156; we should be shepherding Atomic customers to Calypso Stats instead of Jetpack/Odyssey Stats.

**Comment by lakellie** [comment]
This is also happening on self-hosted sites, so redirecting Atomic users elsewhere has not resolved the issue on self-hosted sites. We've received a user report of the bug in 5986419-zen

**Comment by jsnmoon** [comment]
@kangzj, does https://github.com/Automattic/wp-calypso/pull/73741 fix this issue?

**Comment by kangzj** [comment]
@jsnmoon yes - closed as it's resolved already.
