### ISSUE TITLE
Invalid 404 file URLs counted on stats page

### ISSUE THREAD

**Issue by lizkarkoski** [Automattic/jetpack#29430]
#### Steps to reproduce
1. Starting at URL: bwspotlight.com
2. View Stats page
3. Click on one of the counted files
4. Refresh page, view is counted

#### What I expected
With a 404 link it would be expected to not count the view

#### What happened instead
The view is counted

History in this forum thread: https://en.forums.wordpress.com/topic/strange-mass-zip-file-download/#add-note

**Comment by retnonindya** [comment]
Another report: 5778076-zen

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple: Could Not Replicate
- Tested on AT: Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
- Not able to reliably replicate this on a test site. 
- I wonder if this is an issue more with clarity around how certain stats are tracked, rather than a bug?

📌 ACTIONS
- Transferring to Jetpack repo to see if folks who work on Jetpack > Stats can weigh in here?

**Comment by jeherve** [comment]
This should be fixed as of p56BUd-kz-p2#comment-953

I'll close this issue now, feel free to reopen if this starts happening again.

**Comment by i11za** [comment]
User report: 8449402-zd-a8c 

We purged the file in January, but they're still seeing it in Stats. 
Reloading the 404 page increases stats count.

**Comment by kangzj** [comment]
Correct me if mistaken @gibrown, I think we have a project to tackle posts without post ID, which would include 404 pages here: pejTkB-1Br-p2.

**Comment by gibrown** [comment]
Hmmm... that project will take care of 404s of WP pages, but not for file downloads. I think we need to investigate this. Adding it to our maintenance board.
