### ISSUE TITLE
[Block] Payments - Cannot select Donations Form or Premium Content Block type on Simple Site

### ISSUE THREAD

**Issue by cuemarie** [Automattic/jetpack#29640]
### Quick summary

When trying to add a Donations Form to a Premium Plan site, I'm unable to select the "Donations Form" option in the Payments block.  Clicking that option results in no action on the page.

### Steps to reproduce

1. Open a page on a Premium or Personal Plan site, page/post
2. Insert Payments Block
3. Select "Donations Form" type

### What you expected to happen

The Donations From block to be inserted on the page

### What actually happened

Nothing

https://user-images.githubusercontent.com/27249804/227045204-9a150196-e559-40fa-bd2e-819839eef7f6.mp4

### Impact

Some (< 50%)

### Available workarounds?

Not for most users

I found I was able to copy the code for the Donations Form block on an AT site and paste it into my simple site page's code editor; the plan ID and fallback link URLs and such all updated to the correct site.

Pasting this code into a simple site page's code editor, then switching back to visual mode, should allow the user to move forward:

```
<!-- wp:jetpack/donations {"oneTimeDonation":{"show":true,"planId":100,"amounts":[5,15,100],"heading":"Make a one-time donation","extraText":"Your contribution is appreciated.","buttonText":"Donate"},"monthlyDonation":{"show":false,"planId":492,"amounts":[5,15,100],"heading":"Make a monthly donation","extraText":"Your contribution is appreciated.","buttonText":"Donate monthly"},"annualDonation":{"show":false,"planId":493,"amounts":[5,15,100],"heading":"Make a yearly donation","extraText":"Your contribution is appreciated.","buttonText":"Donate yearly"},"showCustomAmount":false,"fallbackLinkUrl":"https://wordpress.com/s-donations/"} -->
<div class="wp-block-jetpack-donations"><h4>Make a one-time donation</h4><p>Your contribution is appreciated.</p><a class="jetpack-donations-fallback-link" href="https://wordpress.com/s-donations/" rel="noopener noreferrer noamphtml" target="_blank">Donate</a></div>
<!-- /wp:jetpack/donations -->
```

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

Replicated with FSE and Classic Themes active

**Comment by cuemarie** [comment]
Escalated here: p1679521739387739-slack-C02FMH4G8

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple: Replicated
     - looks like there's some variance across browsers - troubleshooting happening here: p1679521739387739-slack-C02FMH4G8

📌 FINDINGS/SCREENSHOTS/VIDEO
- In FireFox 111.0.1 (just updated), I'm actually unable to select either the Donations Form or the Premium Content type.  The Payment Buttons option works as expected:

https://user-images.githubusercontent.com/27249804/227052690-87900d1c-4ff6-4c8a-899a-970edbf844ed.mp4

📌 ACTIONS
- Scrubbed; assignment pending
- Transferred to Jetpack repo

**Comment by cuemarie** [comment]
It looks like this is now wordking! Possibly a conflict that was resolved with the release of 15.4.

Ref: p1679559224729229/1679521739.387739-slack-C02FMH4G8

**Comment by WunderBart** [comment]
> It looks like this is now wordking! Possibly a conflict that was resolved with the release of 15.4.

This is still broken with v15.4, but only for users that have the subject blocks disabled in user preferences (see https://github.com/Automattic/jetpack/issues/28523#issuecomment-1503286721). We can leave this issue closed in favor of https://github.com/Automattic/jetpack/issues/28523, though.
