### ISSUE TITLE
Odyssey stats styling seems to be overriding all admin notices in /wp-admin/

### ISSUE THREAD

**Issue by Nic-Sevic** [Automattic/jetpack#31375]
### Impacted plugin

None / Other

### Quick summary

The styling of admin notices seems to be getting overwritten by the styling here: [dde63222](fbhepr%2Skers%2Spnylcfb%2Snccf%2Sbqlffrl%2Qfgngf%2Sfep%2Sfglyrf%2Sjc%2Qnqzva.fpff%3Se%3Qqqr63222-og)

Notices initially load correctly and then the odyssey stats styling is applied. 
This is happening only on site.com/wp-admin and not the /wp-admin/something pages
seems to be happening with all admin notices

### Steps to reproduce

1. On a WoA site (pro/business/ecommerce) force an admin notice to show on /wp-admin/
(An easy to force notice is to activate the anyone can register setting in /wp-admin/options-general.php)
2. Check how the notice displays on a different wp-admin page (ex: wp-admin/options-general.php)
3. compare to styling on /wp-admin/

### A clear and concise description of what you expected to happen.

admin notice styling should be the same on all wp-admin pages, not overwritten 

Expect it to look something like this (left sidebar color would vary)
![2023-06-14 at 14 57](https://github.com/Automattic/jetpack/assets/47717887/e1669926-7356-4a8f-934d-4a1db0b91f60)

### What actually happened

the notice is instead styled like 
![2023-06-14 at 14 58](https://github.com/Automattic/jetpack/assets/47717887/0439bca3-64af-4fb7-b0b1-d641755d9aca)

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Atomic

**Comment by kangzj** [comment]
This is fixed in #78221 - Thanks @dognose24!  and shipped with D113773-code.

**Comment by dognose24** [comment]
@kangzj Thanks for shipping with the Odyssey Stats build! 🚢

**Comment by Nic-Sevic** [comment]
Hey @dognose24 It looks like this partially fixed things but the color of the notice on the lefthand side is still getting overwritten. Currently it seems that regardless of the color it's supposed to show up as it's showing as grey

**Comment by dognose24** [comment]
Hi, @Nic-Sevic! Could you give me more clues (e.g., screenshots) to demonstrate the remaining styling issue? The notice styling on my Atomic site seems reasonable.

<img width="1141" alt="截圖 2023-06-27 上午11 39 04" src="https://github.com/Automattic/jetpack/assets/6869813/e107a5dd-a95d-4766-8c02-13bc09dd8f00">

**Comment by Nic-Sevic** [comment]
Hi @dognose24, when I check my sites I'm still seeing the notice like 
![2023-06-28 at 10 11](https://github.com/Automattic/jetpack/assets/47717887/ff95c9de-2657-4003-967c-f88fe1427c67)

 when it should be like 
![2023-06-28 at 10 11](https://github.com/Automattic/jetpack/assets/47717887/79eeef75-b194-44cb-9762-a846d3526377)

Are you maybe looking on a self-hosted site rather than a WoA site? Or maybe something in your dev site isn't fully matching?

**Comment by dognose24** [comment]
<img width="951" alt="截圖 2023-06-29 上午12 38 35" src="https://github.com/Automattic/jetpack/assets/6869813/08a67a4f-53fd-4d99-8d68-879c4c07380a">

I confirmed the issue was caused by the `.notice__icon-wrapper` [styles](https://github.com/Automattic/wpcomsh/blob/trunk/assets/admin-style.css#L86-L96) of `wpcomsh` overridden by [Calypso Notice component styles](https://github.com/Automattic/wp-calypso/blob/trunk/client/components/notice/style.scss#L99-L109) imported via Odyssey Stats.

Since the notice component would be used spreadly inside Calypso, changing the component styles to CSS modules might break specific existing styling. I would prefer to [increase the specificity](https://github.com/Automattic/wpcomsh/pull/1420) of the `wpcomsh` notice from the source, and the changes look reasonable as well.

**Comment by dd32** [comment]
I've run into some styling issues coming from the `odyssey-stats` styles too, this time that the wp-calypso styles for `.notice:not(.wpcomsh-notice)` is too broad, applying to wp-admin core notices too.

For example, it's visible in the Events widget on self-hosted sites using Jetpack Stats:
<img width="1079" alt="Screenshot 2023-07-06 at 12 58 16 pm" src="https://github.com/Automattic/jetpack/assets/767313/1c62bcaf-5ba7-4924-ac37-d2e9310ee5ee">

Ideally, the component imported from Calypso which styles `.notice` probably needs to be scoped to `body.calypso .notice` or similar.
https://github.com/Automattic/wp-calypso/blob/trunk/apps/odyssey-stats/src/styles/wp-admin.scss

**Comment by dognose24** [comment]
> I've run into some styling issues coming from the odyssey-stats styles too, this time that the wp-calypso styles for .notice:not(.wpcomsh-notice) is too broad, applying to wp-admin core notices too.

Yes, we are conscious that specific resolutions for reported conflict styles [might still cause similar issues](https://github.com/Automattic/wp-calypso/pull/79051/files#diff-495d35474fbde4de50d929b36664a994f4235e25e86b9f3b1da7941ba16da404R20) in the future. 

> Ideally, the component imported from Calypso which styles .notice probably needs to be scoped to body.calypso .notice or similar.

Scoping the Calypso `Notice` component styles could be a fundamental solution. However, I am still [determining the impact](https://github.com/Automattic/wp-calypso/pull/79051#discussion_r1257644950) of refactoring the Calypso `Notice` component [usage with customized overriding styles](https://github.com/search?q=repo%3AAutomattic%2Fwp-calypso+.notice+language%3ASCSS&type=code&l=SCSS&p=1), which could also cause potential issues.

**Comment by dognose24** [comment]
Hi @dd32! Because this issue has been pending for a long time, I cannot reproduce it and your report, as the problem might be resolved during iterations. Could you test for the [situation you encountered](https://github.com/Automattic/jetpack/issues/31375#issuecomment-1622903661) and check if it is still reproducible? Thanks!

**Comment by dd32** [comment]
I'm not able to quickly trigger the issue at hand, but the styles are still applying as the CSS is still overly broad.

Easiest way to see that is to just use the inspector on a `.notice` element.

https://github.com/user-attachments/assets/861f4551-1de3-4b53-882d-e6461003acb3

**Comment by dognose24** [comment]
> but the styles are still applying as the CSS is still overly broad.

> Easiest way to see that is to just use the inspector on a .notice element.

I think this behavior is expected because the `.notice` styles are broadly overridden by the Calypso Notice component. So, we need to restore them in most cases unless a CSS specificity conflict like [this original issue](https://github.com/Automattic/wp-calypso/pull/78221) of `.wpcomsh-notice` is reported.

Related issue: https://github.com/Automattic/wp-calypso/issues/71830.

I would prefer to close this issue because it should have been resolved. Let's see if any other case comes up. What do you think? cc @kangzj 

<img width="578" alt="Image" src="https://github.com/user-attachments/assets/81d8a77d-9464-43d5-a835-536e7ae13b35" />

**Comment by dognose24** [comment]
I have created another issue to track the enhancement: https://github.com/Automattic/red-team/issues/356.

**Comment by dognose24** [comment]
Close as https://github.com/Automattic/jetpack/issues/31375#issuecomment-2760104431 and follow up the potential refactor in https://github.com/Automattic/jetpack/issues/31375#issuecomment-2761247970.
