### ISSUE TITLE
Jetpack Like: Liking a post comment throws a JS error.

### ISSUE THREAD

**Issue by Ninodevo** [Automattic/jetpack#42670]
### Impacted plugin

Jetpack

### Quick summary

Clicking on Jetpack `Like` on a post comment throws a JS error. See screenshot.

![Image](https://uploads.linear.app/f629fcde-6f9b-48e8-8af3-60eed8823bff/634e1745-8d3b-4ea6-9be4-109c9723cdac/fc8888a9-b71d-446a-86a5-75783cdcbde7?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2Y2MjlmY2RlLTZmOWItNDhlOC04YWYzLTYwZWVkODgyM2JmZi82MzRlMTc0NS04ZDNiLTRlYTYtOWJlNC0xMDljOTcyM2NkYWMvZmM4ODg4YTktYjcxZC00NDZhLTg2YTUtNzU3ODNjZGNiZGU3IiwiaWF0IjoxNzcyNzQxOTUxLCJleHAiOjE4MDQzMTI1MTF9.3O--5q_gUZiEXPZ_dzOwnmpGvhMxD_MNioj906pykLM)

Additionaly, probably caused with the same bug. On blog posts, comment Likes are not loading properly. They appear normal on initial page load, however after some time/scrolling/hovering, they change to show "loading..." text, partially duplicated, resulting in a poor UX. See screenshot.

![Image](https://uploads.linear.app/f629fcde-6f9b-48e8-8af3-60eed8823bff/fb3368ee-cebf-4712-8efc-8c1cc5dbaa02/95da42bf-3765-4c83-9737-8971e3a55487?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2Y2MjlmY2RlLTZmOWItNDhlOC04YWYzLTYwZWVkODgyM2JmZi9mYjMzNjhlZS1jZWJmLTQ3MTItOGVmYy04YzFjYzVkYmFhMDIvOTVkYTQyYmYtMzc2NS00YzgzLTk3MzctODk3MWUzYTU1NDg3IiwiaWF0IjoxNzcyNzQxOTUxLCJleHAiOjE4MDQzMTI1MTF9.MCQKXt494SJIwyiLd4DBpDbZ6f7ibE16UHIxN8Yykqk)

* This seems to happen only Jetpack connected sites.
* This is happening in Jetpack Version 14.5-a.6.

### Steps to reproduce

Visit any site that has Jetpack Like for comments enabled.

For example:<br>[https://wptavern.com/serverpress-is-shutting-down](<https://wptavern.com/serverpress-is-shutting-down>)<br>[https://om.co/2025/03/20/has-search-become-just-a-feature/](<https://om.co/2025/03/20/has-search-become-just-a-feature/>)<br>[https://myanime.live/2025/03/24/xian-ni-renegade-immortal-2023-episode-81-english-sub/](<https://myanime.live/2025/03/24/xian-ni-renegade-immortal-2023-episode-81-english-sub/>)

Issue with `Like`:

1. Click on Like.
2. You will get a redirect and there will be an error in the console as in the attached image.

![Image](https://uploads.linear.app/f629fcde-6f9b-48e8-8af3-60eed8823bff/88fda49e-af8f-4ecf-8839-3860a86511d3/6589141f-385c-4176-ba17-6e87fc277111?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2Y2MjlmY2RlLTZmOWItNDhlOC04YWYzLTYwZWVkODgyM2JmZi84OGZkYTQ5ZS1hZjhmLTRlY2YtODgzOS0zODYwYTg2NTExZDMvNjU4OTE0MWYtMzg1Yy00MTc2LWJhMTctNmU4N2ZjMjc3MTExIiwiaWF0IjoxNzcyNzQxOTUxLCJleHAiOjE4MDQzMTI1MTF9.m9SGMQRa5Q1Tbw0UB7tA4Af3IMm5Q1wtmCbu9mw4ooo)

Issue with `Like loading `text:

1. Scroll up/down on the comments section.
2. After a few scrolls you will see the loading text appear on or below the Like button.

![Image](https://uploads.linear.app/f629fcde-6f9b-48e8-8af3-60eed8823bff/d8d6703e-0f7e-495b-a00f-f3858fe3aeed/a9a41972-3886-49f3-ac75-13ba133f6fab?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2Y2MjlmY2RlLTZmOWItNDhlOC04YWYzLTYwZWVkODgyM2JmZi9kOGQ2NzAzZS0wZjdlLTQ5NWItYTAwZi1mMzg1OGZlM2FlZWQvYTlhNDE5NzItMzg4Ni00OWYzLWFjNzUtMTNiYTEzM2Y2ZmFiIiwiaWF0IjoxNzcyNzQxOTUxLCJleHAiOjE4MDQzMTI1MTF9.kEIsISmamNugwbAY7deUsTyMQiLx0F3aiYgfc3OPkGQ)

### Site owner impact

More than 60% of the total website/platform users

### Severity

Moderate

### What other impact(s) does this issue have?

*No response*

### If a workaround is available, please outline it here.

*No response*

### Platform (Simple and/or Atomic)

Atomic

**Comment by jeherve** [comment]
cc @jsnajdr who recently worked on #42515

**Comment by jsnajdr** [comment]
I can reproduce this. It probably predates my recent changes, and dates back to migration away from jQuery. The crashing code treats `link` as a jQuery element, but it's a native DOM element.

This code path is triggered when i) you unlike a comment and ii) go through a login loop (open login popup and proceed after it closes) during the unlike.

I'm working on a fix.

**Comment by jsnajdr** [comment]
The fix is done in the `wpcom` repo, in the scripts served from `widgets.wp.com`. PR no 178117 in the wpcom GH repo.

**Comment by jeherve** [comment]
Thank you for addressing this quickly!

**Comment by jsnajdr** [comment]
The fix has been deployed, closing this as fixed.

**Comment by Ninodevo** [comment]
Hey @jsnajdr is this already on WPCOM? or are we waiting for deployment, because I can still reproduce the issue.

1. I visit https://wptavern.com/serverpress-is-shutting-down
2. Click on Like
3. I get a redirect + error in console

<img width="506" alt="Image" src="https://github.com/user-attachments/assets/8a1b08f2-acc3-46f9-acee-55790f4c9ce8" />

**Comment by jsnajdr** [comment]
@Ninodevo The fix is deployed, but the old version of the script was cached. We now invalidated the cache and the fix should be truly deployed to everyone.

**Comment by kathrynwp** [comment]
@jsnajdr Hey there – I checked https://om.co/2025/03/20/has-search-become-just-a-feature/ to test this.

While I was able to like (and un-like) a comment without getting a console error, I'm still seeing this issue:

<img width="745" alt="Image" src="https://github.com/user-attachments/assets/73b9a715-65eb-4d8c-b449-2252dd30881c" />

Let me know if you still see that as well or if there's anything else you'd like me to test. Thanks!

**Comment by jsnajdr** [comment]
Hi @kathrynwp, thanks for reporting this! It's an unrelated bug, a recent regression, and I'm fixing it in #42739.

The fix is in Jetpack code, and the om.co site will be fixed only after a new version of the Jetpack plugin is installed there.

**Comment by kathrynwp** [comment]
Thank you so much, @jsnajdr!
