### ISSUE TITLE
Notifications: WebSocket connection blocks pages from back/forward cache (bfcache) eligibility

### ISSUE THREAD

**Issue by westonruter** [Automattic/jetpack#45149]
### Impacted plugin

Jetpack

### Quick summary

When the Notifications module is active, a WebSocket is open on every page when a user is logged-in and the Admin Bar is showing. As noted in the web.dev article on [Back/forward cache](https://web.dev/articles/bfcache), such WebSocket connections make pages ineligible for bfcache. This means that users cannot take advantage of instant back/forward navigations. This was previously in https://github.com/Automattic/jetpack/pull/44322.

When Jetpack's open WebSocket is on the page, the Back/forward cache panel in Chrome DevTools reports the following:

> <img width="867" height="223" alt="Image" src="https://github.com/user-attachments/assets/1bd83b1c-0df2-4e3b-9011-1abdc5ff03af" />

This connection is opened via an iframe'd page located at [https://public-api.wordpress.com/wp-admin/rest-proxy/?v=2.0](https://public-api.wordpress.com/wp-admin/rest-proxy/?v=2.0)

To fix this issue, the aforementioned article advises to [Close open connections before the user navigates away](https://web.dev/articles/bfcache#close-open-connections).

Guidance, with code samples, was also recently added to MDN: [Working with the bfcache](https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API/Writing_WebSocket_client_applications#working_with_the_bfcache).

### Steps to reproduce

1. Enable the Notifications module
2. Navigate from the WP Admin dashboard to another admin screen, and then try navigating back.
3. Notice that the navigation is not instant, even when you have the [No-cache BFCache](https://wordpress.org/plugins/nocache-bfcache/) plugin active (soon to be [renamed](https://github.com/westonruter/nocache-bfcache/pull/49) “Instant Back/Forward”). Confirm this via a bfcache test in Chrome DevTools.

### Site owner impact

More than 60% of the total website/platform users

### Severity

Minor

### What other impact(s) does this issue have?

No revenue impact

### If a workaround is available, please outline it here.

As [advised in the FAQ](https://github.com/westonruter/nocache-bfcache?tab=readme-ov-file#how-can-i-enable-bfcache-when-jetpack-is-active) for the No-cache BFCache plugin, a workaround is to just disable the Notifications module.

### Platform (Simple and/or Atomic)

Self-hosted

**Comment by haqadn** [comment]
Thanks for the report @westonruter. It should be solved now.

**Comment by gilbertococchi** [comment]
Wow, this is great news, thanks @haqadn for fixing this!

**Comment by westonruter** [comment]
This seems improved, but still not 100% resolved. I just tested from the WP Admin, and I'm getting about 50% success for bfcache:

https://github.com/user-attachments/assets/b897ee6c-fd78-4cac-86c7-d3c3ef3b4450

**Comment by haqadn** [comment]
I've deployed another patch. Please let me know if you find anything else. @westonruter

**Comment by westonruter** [comment]
@haqadn Success!

https://github.com/user-attachments/assets/ab4260fd-fea3-4e68-b507-e6272bb25c09

**Comment by gilbertococchi** [comment]
BTW: @haqadn did also restart your WebSocket connection when `pageshow` with `event.persisted=true` triggers?

This is important so a page restored from BFCache would restart the WebSocket connection otherwise the user will go back to a page with the connection closed.

**Comment by haqadn** [comment]
> BTW: [@haqadn](https://github.com/haqadn) did also restart your WebSocket connection when `pageshow` with `event.persisted=true` triggers?
> 
> This is important so a page restored from BFCache would restart the WebSocket connection otherwise the user will go back to a page with the connection closed.

Yes
