### ISSUE TITLE
VideoPress: space storage limits not visible to user

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#6003]
#### Steps to reproduce the issue

0. Start from a site using a Jetpack Premium Plan.
1. Upload a lot of big videos, enough to go over the 13Go quota included in Jetpack Premium.

How do you know how much space you have left? What happens when you reach your quota? It turns out you reach it after only 3Go instead of 13G0, and the only way to figure that out is to check the response you get when trying to upload a new video:

```
{"error":"upload_error","message":"Not enough space to upload. 589,305 KB needed. Back"}
```

Related: #5986

**Comment by aheckler** [comment]
3069502-t

**Comment by danjjohnson** [comment]
3070564-t

**Comment by danjjohnson** [comment]
Is there anything we can do at this stage for users running into this limit?

**Comment by jeherve** [comment]
@dbtlr Any idea about where we could start to get this fixed? 

Thanks!

**Comment by jeherve** [comment]
More discussion in pMz3w-6Dm-p2

**Comment by rickybanister** [comment]
cc @MichaelArestad let's discuss a few ideas I have for this.

**Comment by MichaelArestad** [comment]
@rickybanister okay. Can you elaborate?

**Comment by jeherve** [comment]
More discussion and mockups in p6TEKc-14c-p2

**Comment by rickybanister** [comment]
@MichaelArestad I think @jeherve wrangled what I meant ^

Basically we can introduce a storage limit indicator in the media modal, and hopefully also trigger a notification/email when a user gets close. 

We'll also want to have more of an upgrade banner vs an error notice when a user actually tries to upload a video that's too large and it fails. An error won't help them in that moment, but a banner with a path to expand their storage would.

**Comment by tmmbecker** [comment]
3059867-t

The user didn't reach out about this issue in particular but now that I fixed his other problem, he's ready to do a mass upload of videos. I proactively warned him about this, so I'm adding it here.

**Comment by aheckler** [comment]
cc @MichaelArestad @rickybanister @beaulebens Any updates on this? Seems urgent given that people are paying money specifically to get more space but aren't getting it. :/

**Comment by MichaelArestad** [comment]
@aheckler No, but if it involves an upgrade banner, we may want to look at it along with #6449

**Comment by alexpooley** [comment]
@MichaelArestad @aheckler No upgrade banner involved. It's a really straight forward issue. We've paid to get 13GB of storage, and we're only allowed to upload 3GB. Trying to upload more data triggers an upload error that we're out of space. This is all through the wordpress.com interface.

**Comment by beaulebens** [comment]
We're getting this fixed right now. It turns out that these accounts were not being properly flagged as paid by our systems, so they were being restricted similarly to a free WordPress.com account. The fix should be purely on our end, and won't require a plugin release as far as we can tell so far.

**Comment by dbtlr** [comment]
The plans should be fixed now and providing 13GB and Unlimited data as advertised.

**Comment by lamdayap** [comment]
#3107757-t

**Comment by jeherve** [comment]
@dbtlr Are the changes already live? I still receive the following error on a site that's just below the 3GB limit and on a Premium plan:

`{"error":"upload_error","message":"Not enough space to upload. 625,092 KB needed. Back"}`

**Comment by rickybanister** [comment]
Any updates here @dbtlr?

**Comment by dbtlr** [comment]
@rickybanister: @jeherve confirmed this to be working now last week. :)

**Comment by aheckler** [comment]
@dbtlr By "this" I assume you mean that upload limits are being set correctly? What about the user's quota/usage? Are we surfacing that information to them anywhere?

**Comment by dbtlr** [comment]
@aheckler there is another Calypso related task for that part.

**Comment by aheckler** [comment]
@dbtlr Do you have a link? A quick search didn't reveal anything for me.

I only ask because, at some point, an HE will have to sweep back through the tickets mentioned here and respond to all the users that A) the quota is now fixed, and B) they can now see that information in place X, wherever that ends up being.

**Comment by jeherve** [comment]
From #6742

> We have a storage indicator component in Calypso. I'd like to see us make that available in dops-components so that we can display a video storage indication in the /settings/writing/video card once activated. 

<img width="1001" alt="screen shot 2017-03-24 at 11 38 46 am" src="https://cloud.githubusercontent.com/assets/437258/24301725/b6aeb772-1086-11e7-8205-f74d4070560e.png">

**Comment by ntpixels** [comment]
3265073-t

**Comment by donnapep** [comment]
Sounds like this will be resolved by https://github.com/Automattic/wp-calypso/issues/12507.

**Comment by jeherve** [comment]
Looks like all what's left to do now is to port https://github.com/Automattic/wp-calypso/pull/14229 to wp-admin

**Comment by jeherve** [comment]
also in 797650-zen

**Comment by tmmbecker** [comment]
Even though there are no storage limits, we do have a 2 TB soft limit in place. It would be nice for users to see how much storage they've used. It's not in Calypso either. 

Requested in 3092734-zen
