### ISSUE TITLE
Video Widget: videos inserted from URL have wonky spacing

### ISSUE THREAD

**Issue by designsimply** [Automattic/jetpack#8215]
#### Steps to reproduce the issue

1. Go to My Sites > Customize > Widgets > [widget area] > Add a Widget > Video.
1. Click the "Add Video" button, the "Insert from URL" link on the left, then paste in a YouTube video link (i.e. https://www.youtube.com/watch?v=tgbNymZ7vqY).
1. Click the "Add to Widget" button.
1. Click the Publish" button to save changes.
1. View the front end where the video is visible.
1. Check to see whether the video appears with the proper dimensions or whether it has extra 

<strong>Result:</strong> the video does not display correctly—it has extra spacing around the video that shouldn't be there.

![screen shot 2017-11-20 at mon nov 20 11 41 30 am](https://user-images.githubusercontent.com/1119271/33035369-1ad46d54-cde8-11e7-86e7-858ea9b7829f.png)
<sup>Seen at https://design5279.wordpress.com/ (wpcom simple) with the Twenty Seventeen theme applied using Firefox 57.0 on Mac OS X 10.13.1.</sup>

#### What I expected

I expected that embedding a video into a widget area using the Video Widget would result in a video sized correctly.

#### What happened instead

Videos embedded into a widget area using the Video Widget result in a black box with extra spacing where it should not be.

Internal refs: 

* "it's an issue related to adding the jp resizer by default" - p1511194590000457-slack-triage
* see patch D8373-code - p1511194590000457-slack-apollo

**Comment by designsimply** [comment]
/hat tip @darnelldibbles for the original Trac ticket 7957-wpcom and forums report link 882990-f.

This is how the sidebar looks when a video URL is added via the Video Widget:

<img width="422" alt="sykthzugo8" src="https://user-images.githubusercontent.com/1119271/33036219-f52a5a98-cdea-11e7-912c-e71e6625cd96.png">


And when set to full screen:

<img width="1000" alt="zbpqv1vfmh-2000x2000" src="https://user-images.githubusercontent.com/1119271/33036211-f237e31e-cdea-11e7-9b77-1a0a55b9f71e.png">

**Comment by designsimply** [comment]
/hat tip @kristarella for the chat report at 951288-hc.

<blockquote>I tested with several themes and different YouTube videos and all had excess grey space in the widget, and a tiny video in the full screen view.</blockquote>

**Comment by designsimply** [comment]
/hat tip @vparkhere for the Trac ticket at 7915-wpcom and the email report at 3319036-t.

**Comment by designsimply** [comment]
/hat tip @rachelmcr for testing and confirming the issue at 7957-wpcom #comment:3.

**Comment by designsimply** [comment]
/hat tip @laurelfulford for the live chat at 957298-hc and the email follow-up at 778822-zd-woothemes.

**Comment by designsimply** [comment]
/hat tip @scosgro for the testing (theme Pique) and the email report at 773311-zd-woothemes.

**Comment by designsimply** [comment]
/hat tip @otpidusprime for the email report at 777316-zd-woothemes.

**Comment by designsimply** [comment]
/hat tip @kathrynwp for the forums report at https://en.forums.wordpress.com/topic/dara-theme-no-full-screen-on-video-widget

**Comment by designsimply** [comment]
/hat tip @edequalsawesome for the chat report at 951337-hc and the email follow-up at 779731-zd-woothemes and for noting the theme name! (Theme: Broadsheet)

<blockquote>I tested this and was able to replicate it with the Broadsheet theme, but the full-screen video player worked as expected when I tested with Twenty Seventeen.</blockquote>

**Comment by designsimply** [comment]
/hat tip @scosgro for the chat report at 56811-hc. (Theme: Big Brother)

**Comment by designsimply** [comment]
/hat tip Pratik for the email report at 787263-zd-woothemes. (Theme: Heart and Style)

**Comment by designsimply** [comment]
/hat tip @hacchism for the email report at 787263-zd-woothemes. (Theme: Heart and Style)

**Comment by designsimply** [comment]
/hat tip @eduardozulian for noting a previous report is checking back in at 1006523-hc.

**Comment by designsimply** [comment]
/hat tip @adelineyaw for the email report at 795115-zd-woothemes.

**Comment by designsimply** [comment]
/hat tip @cscheer for the report in Slack at p1510938318000593-slack-triage.

**Comment by designsimply** [comment]
/hat tip @katinthehatsite for the chat report at 1038621-hc and for noting a workaround!

<blockquote>As a temporary workaround to fix the size, I have added text widget + embedded the video through a shortcode eg. [youtube]</blockquote>

**Comment by designsimply** [comment]
/hat tip @wynwinfor the chat report at 1045426-hc and the follow-up ticket at 803337-zd-woothemes.

**Comment by designsimply** [comment]
/hat tip Tiffany V for the chat report at 957298-hc and the follow-up email at 778822-zd-woothemes.

**Comment by designsimply** [comment]
Marked 4735-wpcom as a duplicate.

**Comment by oskosk** [comment]
This is addressed by r165801-wpcom and D369-code for .com sites (not deployed yet). #8225 for Jetpack sites (not merged yet). Will close this issue when #8225 gets merge.

**Comment by chad1008** [comment]
This still appears to be affecting Jetpack (and Atomic) sites running Radcliffe 2.

Reported here: 816487-zd-woothemes

I tested a Youtube video in the Video Widget on a WordPress.com Simple, WordPress.com Atomic, and a self hosted (Pressable) Jetpack site. All three were running Radcliffe 2.

The Simple site worked fine - Atomic and Jetpack still displayed the video thumbnail sized in full screen mode.

cc @oskosk

**Comment by oskosk** [comment]
Thanks @chad1008 will check.
